apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: triton-rollout
  namespace: triton
spec:
  replicas: 2
  selector:
    matchLabels:
      app: triton
  template:
    metadata:
      labels:
        app: triton
    spec:
      containers:
        - name: triton
          image: nginx:1.29   # Replace with your image
          ports:
            - containerPort: 8080
  strategy:
    canary:
      steps:
        - setWeight: 25
        - pause: {duration: 30s}
        - setWeight: 50
        - pause: {}
        - setWeight: 100
