apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: triton-rollout
spec:
  replicas: 1
  selector:
    matchLabels:
      app: triton
  strategy:
    canary:
      steps:
        - setWeight: 50
        - pause: { duration: 30s }
  template:
    metadata:
      labels:
        app: triton
    spec:
      initContainers:
        - name: sync-models
          image: google/cloud-sdk:latest
          command:
            - /bin/sh
            - -c
            - |
              echo "Activating service account..."
              gcloud auth activate-service-account --key-file=/secrets/eminent-cache-456900-t9-6e636af0d847.json
              gsutil -m cp -r gs://your-bucket-name/models/* /models/
          volumeMounts:
            - name: model-repo
              mountPath: /models
            - name: gcp-sa
              mountPath: /secrets
              readOnly: true
      containers:
        - name: triton
          image: nvcr.io/nvidia/tritonserver:24.04-py3
          args: ["tritonserver", "--model-repository=/models"]
          ports:
            - containerPort: 8000
            - containerPort: 8001
          volumeMounts:
            - name: model-repo
              mountPath: /models
      volumes:
        - name: model-repo
          persistentVolumeClaim:
            claimName: triton-model-pvc
        - name: gcp-sa
          secret:
            secretName: gcs-sa-secret
